// Inlines the ES modules and stylesheet into two self-contained outputs:
//   dist/index.html                - the standalone page (same as the live site, single file)
//   dist/sunday-light-meter.liquid - a Shopify theme section for sundaylight.cc
// No dependencies: modules are concatenated in dependency order with their
// import/export statements stripped, so every top-level name must be unique.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, p), 'utf8');

const ORDER = ['src/cie-data.js', 'src/lm4-model-data.js', 'src/colour.js', 'src/protocol.js', 'src/lm3.js', 'src/lm4.js', 'src/meter.js', 'src/app.js'];

const seen = new Map();
const parts = ORDER.map((file) => {
  let src = read(file);
  src = src.replace(/^import\s[\s\S]*?from\s+'[^']+';\s*$/gm, '');
  src = src.replace(/^export\s+(const|let|var|function|class|async function)\s/gm, '$1 ');
  if (/^export\s/m.test(src)) throw new Error(`${file}: unsupported export form left after stripping`);
  for (const m of src.matchAll(/^(?:const|let|var|function|class|async function)\s+([A-Za-z_$][\w$]*)/gm)) {
    const name = m[1];
    if (seen.has(name)) throw new Error(`top-level name "${name}" declared in both ${seen.get(name)} and ${file}`);
    seen.set(name, file);
  }
  return `// ---- ${file} ----\n${src.trim()}\n`;
});
const bundle = parts.join('\n');
const css = read('src/style.css');

if (/\{\{|\{%/.test(bundle) || /\{\{|\{%/.test(css)) throw new Error('bundle contains Liquid delimiters');
if (/<\/script/i.test(bundle)) throw new Error('bundle contains a closing script tag');

// Standalone page
const html = read('index.html')
  .replace('<link rel="stylesheet" href="src/style.css">', `<style>\n${css}\n</style>`)
  .replace('<script type="module" src="src/app.js"></script>', `<script type="module">\n${bundle}\n</script>`);

// Shopify section
const liquid = `{%- comment -%}
  Sunday Light Meter - Web Bluetooth light meter for the Opple Light Master 3/4
  with a Sunday light calibration check. Generated by scripts/build.mjs in
  https://github.com/natmart-in/sunday-light-meter - edit the source, not this file.
{%- endcomment -%}
<section class="sunday-light-meter-section color-{{ section.settings.color_scheme }}" id="light-meter">
  <div class="sunday-light-meter-section__inner">
    {%- if section.settings.heading != blank -%}
      <h2 class="sunday-light-meter-section__title">{{ section.settings.heading }}</h2>
    {%- endif -%}
    {%- if section.settings.text != blank -%}
      <div class="sunday-light-meter-section__text">{{ section.settings.text }}</div>
    {%- endif -%}
    <div id="sunday-light-meter"></div>
  </div>
</section>
{% raw %}
<style>
.sunday-light-meter-section { padding: 48px 0 24px; }
.sunday-light-meter-section__inner { max-width: 1080px; margin: 0 auto; padding: 0 20px; }
.sunday-light-meter-section__title { font-family: var(--sunday-heading, 'DM Sans', sans-serif); font-weight: 500; letter-spacing: -0.03em; line-height: 1.08; font-size: clamp(34px, 5vw, 52px); margin: 0 0 12px; }
.sunday-light-meter-section__text { font-family: var(--sunday-body, 'Inter', sans-serif); font-size: 17px; line-height: 1.6; color: #78716c; max-width: 60ch; margin: 0 0 28px; }
.sunday-light-meter-section .slm { padding-left: 0; padding-right: 0; }
${css}
</style>
<script type="module">
${bundle}
</script>
{% endraw %}
{% schema %}
{
  "name": "Sunday Light Meter",
  "tag": "section",
  "class": "section-sunday-light-meter",
  "settings": [
    { "type": "color_scheme", "id": "color_scheme", "label": "Color scheme", "default": "scheme-1" },
    { "type": "text", "id": "heading", "label": "Heading", "default": "Measure the light you actually get" },
    { "type": "richtext", "id": "text", "label": "Intro", "default": "<p>Connect an Opple Light Master 3 or 4 over Bluetooth to read brightness, colour temperature, Duv and colour rendering live - then check how close your Sunday light lands to the setting in the app.</p>" }
  ],
  "presets": [{ "name": "Sunday Light Meter" }]
}
{% endschema %}
`;

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist', 'index.html'), html);
writeFileSync(join(root, 'dist', 'sunday-light-meter.liquid'), liquid);
console.log(`dist/index.html ${(html.length / 1024).toFixed(1)} KB, dist/sunday-light-meter.liquid ${(liquid.length / 1024).toFixed(1)} KB`);
